// @generated by Hollywood. Do not edit by hand.

import { runGitHubAction } from "@dedalus-labs/hollywood/action-runtime";
import { verifyRunnerImage } from "@/gha/runner-image-actions.ts";

void runGitHubAction(verifyRunnerImage);
