// @generated by Hollywood. Do not edit by hand.

import { runGitHubAction } from "@dedalus-labs/hollywood/action-runtime";
import { leaveFlower } from "../../../../gha/flowers.ts";

void runGitHubAction(leaveFlower);
