import { defineConfig } from "tsdown";

const banner = "/* @generated by npm run build. Do not edit by hand. */";
const neverBundle = [/^@actions\//, "esbuild", "yaml"];

export default defineConfig([
	{
		banner: { js: banner },
		clean: true,
		deps: { neverBundle },
		dts: true,
		entry: {
			"action-runtime": "src/action-runtime.ts",
			environments: "src/environments.ts",
			expr: "src/expr.ts",
			index: "src/index.ts",
		},
		fixedExtension: false,
		format: "esm",
		platform: "node",
	},
	{
		banner: { js: banner },
		clean: false,
		deps: {
			neverBundle,
			onlyBundle: ["@commander-js/extra-typings", "commander"],
		},
		dts: false,
		entry: { cli: "src/cli.ts" },
		fixedExtension: false,
		format: "esm",
		platform: "node",
	},
]);
