import { defineConfig } from "tsdown";

const banner = "/* @generated by npm run build. Do not edit by hand. */";
const neverBundle = [/^@actions\//, "esbuild", "yaml"];
const productionDefines = { "import.meta.vitest": "undefined" };
const target = "node20";

export default defineConfig([
	{
		banner: { js: banner },
		clean: true,
		define: productionDefines,
		deps: { neverBundle },
		dts: true,
		entry: {
			"action-runtime": "src/action-runtime.ts",
			environments: "src/environments.ts",
			expr: "src/expr.ts",
			index: "src/index.ts",
		},
		fixedExtension: false,
		format: "esm",
		platform: "node",
		target,
	},
	{
		banner: { js: banner },
		clean: false,
		define: productionDefines,
		deps: {
			neverBundle,
			onlyBundle: [
				"@commander-js/extra-typings",
				"commander",
				"fdir",
				"picomatch",
				"tinyglobby",
			],
		},
		dts: false,
		entry: { cli: "src/cli.ts" },
		fixedExtension: false,
		format: "esm",
		platform: "node",
		target,
	},
]);
