// @generated by Hollywood. Do not edit by hand.

import { runGitHubAction } from "@dedalus-labs/hollywood/action-runtime";
import { checkRuntime } from "@/gha/ci.ts";

void runGitHubAction(checkRuntime);
