// @generated by Hollywood. Do not edit by hand.

import { runGitHubAction } from "@dedalus-labs/hollywood/action-runtime";
import { validateReleaseCandidate } from "@/gha/release-actions.ts";

void runGitHubAction(validateReleaseCandidate);
