// @generated by Hollywood. Do not edit by hand.

import { runGitHubAction } from "@dedalus-labs/hollywood/action-runtime";
import { publishNpmPackage } from "@/gha/publish-npm.ts";

void runGitHubAction(publishNpmPackage);
