// @generated by Hollywood. Do not edit by hand.

import { runGitHubAction } from "@dedalus-labs/hollywood/action-runtime";
import { checkParallelModel } from "@/gha/models.ts";

void runGitHubAction(checkParallelModel);
