# Copyright (c) 2026 Dedalus Labs, Inc. and its contributors
# SPDX-License-Identifier: MIT
---
blank_issues_enabled: false
contact_links:
  - name: Security vulnerability
    url: mailto:security@dedaluslabs.ai
    about: Email security vulnerabilities privately.
