// @generated by Hollywood. Do not edit by hand.

import { runGitHubAction } from "@dedalus-labs/hollywood/action-runtime";
import { createGitHubRelease } from "@/gha/publish-npm.ts";

void runGitHubAction(createGitHubRelease);
