// @generated by Hollywood. Do not edit by hand.

import { runGitHubAction } from "@dedalus-labs/hollywood/action-runtime";
import { checkVouch } from "../../../../gha/cla.ts";

void runGitHubAction(checkVouch);
