// @generated by Hollywood. Do not edit by hand.

import { runGitHubAction } from "@dedalus-labs/hollywood/action-runtime";
import { testContainerProvider } from "@/gha/ci.ts";

void runGitHubAction(testContainerProvider);
