import { readdir } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { build } from "esbuild";

const root = dirname(fileURLToPath(import.meta.url));
const actionsDir = join(root, "..", ".github", "actions");

const entries = await actionEntrypoints(actionsDir);
await Promise.all(entries.map(buildAction));

async function actionEntrypoints(dir) {
	const entries = [];
	for (const entry of await readdir(dir, { withFileTypes: true })) {
		const path = join(dir, entry.name);
		if (entry.isDirectory()) {
			entries.push(...(await actionEntrypoints(path)));
			continue;
		}
		if (entry.isFile() && path.endsWith(join("src", "index.ts"))) {
			entries.push(path);
		}
	}
	return entries.sort();
}

async function buildAction(entry) {
	await build({
		banner: {
			js: [
				"/* @generated by npm run build:actions. Do not edit by hand. */",
				'import { createRequire } from "node:module";',
				"const require = createRequire(import.meta.url);",
			].join("\n"),
		},
		bundle: true,
		define: { "import.meta.vitest": "undefined" },
		entryPoints: [entry],
		format: "esm",
		outfile: join(dirname(dirname(entry)), "dist", "index.js"),
		platform: "node",
		target: "node24",
	});
}
