import { mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { basename, dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { build } from "esbuild";

import {
	withContainer,
	type ContainerOptions,
	type ContainerProvider,
} from "./container";
import { toGitHubName } from "./names";

export type ContainerActionOptions = Readonly<{
	actionRuntime?: string;
	exportName: string;
	hostExec?: ContainerOptions["hostExec"];
	image: string;
	provider: ContainerProvider;
	source: string;
	with: Readonly<Record<string, string>>;
	workspace: string;
}>;

export type ContainerActionResult = Readonly<{
	outputs: Readonly<Record<string, string>>;
	stderr: string;
	stdout: string;
}>;

export const runContainerAction = async (
	options: ContainerActionOptions,
): Promise<ContainerActionResult> => {
	const directory = await mkdtemp(`${tmpdir()}/hollywood-action-`);
	const bundle = join(directory, "action.mjs");
	try {
		await buildContainerAction(
			options.source,
			options.exportName,
			bundle,
			options.actionRuntime ?? fileURLToPath(new URL("./action-runtime.js", import.meta.url)),
		);
		return await withContainer(
			{
				actionBundle: bundle,
				image: options.image,
				provider: options.provider,
				workspace: options.workspace,
				...(options.hostExec === undefined ? {} : { hostExec: options.hostExec }),
			},
			async ({ exec }) => {
				const command = await exec("node", ["/github/workflow/action.mjs"], {
					env: inputEnvironment(options.with),
				});
				const output = await exec("cat", ["/github/workflow/result.json"]);
				return {
					outputs: parseActionResult(output.stdout),
					stderr: command.stderr,
					stdout: command.stdout,
				};
			},
		);
	} finally {
		await rm(directory, { force: true, recursive: true });
	}
};

const buildContainerAction = async (
	source: string,
	exportName: string,
	outfile: string,
	actionRuntime: string,
): Promise<void> => {
	const resolved = resolve(source);
	await build({
		banner: {
			js: [
				"/* @generated by Hollywood for an ephemeral local run. */",
				'import { createRequire } from "node:module";',
				"const require = createRequire(import.meta.url);",
			].join("\n"),
		},
		bundle: true,
		define: { "import.meta.vitest": "undefined" },
		format: "esm",
		outfile,
		platform: "node",
		stdin: {
			contents: actionEntrypoint(basename(resolved), exportName, actionRuntime),
			resolveDir: dirname(resolved),
			sourcefile: ".hollywood-action.ts",
		},
		target: "node24",
	});
};

const actionEntrypoint = (source: string, exportName: string, actionRuntime: string): string => {
	if (exportName !== "default" && !/^[A-Za-z_$][\w$]*$/.test(exportName)) {
		throw new Error(`Invalid TypeScript export name: ${exportName}.`);
	}
	const actionImport =
		exportName === "default"
			? `import scriptAction from ${JSON.stringify(`./${source}`)};`
			: `import { ${exportName} as scriptAction } from ${JSON.stringify(`./${source}`)};`;
	return [
		'import { writeFile } from "node:fs/promises";',
		`import { runGitHubAction } from ${JSON.stringify(actionRuntime)};`,
		actionImport,
		"",
		"const outputs = await runGitHubAction(scriptAction);",
		'if (outputs !== undefined) await writeFile("/github/workflow/result.json", JSON.stringify(outputs));',
		"",
	].join("\n");
};

const inputEnvironment = (
	inputs: Readonly<Record<string, string>>,
): Readonly<Record<string, string>> =>
	Object.fromEntries(
		Object.entries(inputs).map(([name, value]) => [
			`INPUT_${toGitHubName(name).replaceAll(" ", "_").toUpperCase()}`,
			value,
		]),
	);

export const parseActionResult = (content: string): Readonly<Record<string, string>> => {
	const parsed: unknown = JSON.parse(content);
	if (
		parsed === null ||
		typeof parsed !== "object" ||
		Array.isArray(parsed) ||
		Object.values(parsed).some((value) => typeof value !== "string")
	) {
		throw new Error("Container action returned invalid outputs. Every output value must be a string.");
	}
	return parsed as Readonly<Record<string, string>>;
};
