import * as assert from "node:assert/strict";
import { mkdtemp, readFile, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { test } from "vitest";

import { generateActionEntrypointFile, generateActionFile } from "./generate";
import { action, stringOutput } from "./script";
import { writeGeneratedFiles } from "./files";

const helloAction = action({
	name: "hello",
	description: "Say hello from a generated GitHub action.",
	inputs: {},
	outputs: {
		greeting: stringOutput({ description: "Generated greeting." }),
	},
	run: async () => ({ greeting: "hello" }),
});

test("writeGeneratedFiles writes generated files under outputDir", async () => {
	const outputDir = await mkdtemp(join(tmpdir(), "hollywood-files-"));
	const generatedAt = new Date("2026-05-14T00:00:00.000Z");
	const files = [
		generateActionFile(helloAction, {
			sourcePath: "ci/hello.ts",
			actionsDir: ".github/actions",
			generatedAt,
		}),
		generateActionEntrypointFile(helloAction, {
			sourcePath: "ci/hello.ts",
			actionsDir: ".github/actions",
			exportName: "helloAction",
			generatedAt,
		}),
	];

	const firstWrite = await writeGeneratedFiles(files, { outputDir });

	assert.deepEqual(
		firstWrite.map(({ path, status }) => ({ path, status })),
		[
			{ path: ".github/actions/hello/action.yml", status: "created" },
			{ path: ".github/actions/hello/src/index.ts", status: "created" },
		],
	);
	assert.match(
		await readFile(join(outputDir, ".github/actions/hello/action.yml"), "utf8"),
		/^# @generated by Hollywood at 2026-05-14T00:00:00.000Z\. Do not edit by hand\./,
	);

	const secondWrite = await writeGeneratedFiles(files, { outputDir });

	assert.deepEqual(
		secondWrite.map(({ path, status }) => ({ path, status })),
		[
			{ path: ".github/actions/hello/action.yml", status: "unchanged" },
			{ path: ".github/actions/hello/src/index.ts", status: "unchanged" },
		],
	);

	await writeFile(join(outputDir, ".github/actions/hello/src/index.ts"), "old");

	const thirdWrite = await writeGeneratedFiles(files, { outputDir });

	assert.equal(thirdWrite[1]?.status, "updated");
});

test("writeGeneratedFiles rejects paths outside outputDir", async () => {
	const outputDir = await mkdtemp(join(tmpdir(), "hollywood-files-"));
	await assert.rejects(
		() =>
			writeGeneratedFiles(
				[
					{
						sourcePath: "ci/escape.ts",
						path: "../escape.ts",
						header: "// generated",
						content: "nope\n",
					},
				],
				{ outputDir },
			),
		/generated file path escapes outputDir/,
	);
});
